name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          pull-request-header: ":robot: *beep* *boop* I have created a release"
          command: manifest
